name: terceira_prova
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  floor: ^1.4.2
  shared_preferences: ^2.2.2
  connectivity: ^3.0.6
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
    #1) Crie o aplicativo “terceira_prova” que deve funcionar para dispositivos Android ou iOS. Crie a
#Widget TelaHome que configura um Widget MaterialApp. Crie um Widget TelaHome que deve
#apresentar informações sobre o aplicativo. Adicione um ícone customizado para o aplicativo utilizando
#o pacote flutter_launcher_icons (https://pub.dev/packages/flutter_launcher_icons) (0,5 ponto)
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  web: true
  image_path: "assets/pokeball.png"

flutter:
  uses-material-design: true
